# Generated by Django 5.1.15 on 2026-08-28 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_number', models.PositiveIntegerField(help_text='Sequential public number; never reused.', unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='One-line curatorial subtitle.', max_length=240)),
                ('period', models.CharField(help_text='e.g. c. 1880 or dated 1887', max_length=120)),
                ('period_sort', models.IntegerField(help_text='Numeric year for filtering/sorting.')),
                ('region', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('material', models.CharField(help_text='Middot-separated, hierarchical.', max_length=240)),
                ('maker', models.CharField(blank=True, help_text='Attributed maker/workshop, if documented.', max_length=200)),
                ('attribution', models.CharField(blank=True, help_text='Cataloguing term: attributed to / circle of / manner of.', max_length=240)),
                ('story', models.TextField(help_text='The historical narrative.')),
                ('story_lede', models.TextField(blank=True, help_text='Opening paragraph, displayed larger.')),
                ('condition', models.TextField(blank=True)),
                ('condition_grade', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Fair', 'Fair')], max_length=40)),
                ('dimensions', models.CharField(blank=True, max_length=200)),
                ('weight', models.CharField(blank=True, max_length=100)),
                ('frame_count', models.PositiveIntegerField(default=36, help_text='Frames in the turntable sequence.')),
                ('hero_frame', models.PositiveIntegerField(default=0)),
                ('accent_hex', models.CharField(default='#6F5B45', help_text='Object-derived accent for cards.', max_length=7)),
                ('status', models.CharField(choices=[('available', 'Available for acquisition'), ('reserved', 'Under consideration'), ('acquired', 'In a private collection'), ('archive', 'Archived')], default='available', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['object_number'],
            },
        ),
        migrations.CreateModel(
            name='Chronicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('standfirst', models.TextField(blank=True)),
                ('body', models.TextField(help_text='Markdown-lite: blank-line paragraphs, ## headings, > quotes, - lists.')),
                ('published_at', models.DateField()),
                ('reading_minutes', models.PositiveIntegerField(default=6)),
                ('object_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chronicles', to='collection.artifact')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='collection.artifact')),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('detail', models.TextField(blank=True)),
                ('frame_index', models.PositiveIntegerField(default=0)),
                ('x', models.FloatField(help_text='0..1 horizontal position within the frame.')),
                ('y', models.FloatField(help_text='0..1 vertical position within the frame.')),
                ('kind', models.CharField(choices=[('mark', "Maker's mark"), ('engraving', 'Engraving / signature'), ('patina', 'Patina / surface'), ('damage', 'Damage / wear'), ('restoration', 'Restoration'), ('craft', 'Craftsmanship detail')], default='mark', max_length=40)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_points', to='collection.artifact')),
            ],
            options={
                'ordering': ['frame_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProvenanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='As documented: 1887, c. 1890, 1924.', max_length=40)),
                ('year_sort', models.IntegerField(help_text='Numeric sort year.')),
                ('event', models.TextField(help_text='What happened, in one or two precise sentences.')),
                ('evidence', models.CharField(blank=True, help_text='Citation for the claim, if any.', max_length=300)),
                ('undocumented', models.BooleanField(default=False, help_text='Mark a gap in the record honestly.')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provenance', to='collection.artifact')),
            ],
            options={
                'ordering': ['year_sort', 'id'],
            },
        ),
    ]
