# Generated by Django 5.1.15 on 2026-08-28 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='stage',
            field=models.CharField(choices=[('enquire', 'Enquiry received'), ('discuss', 'In discussion'), ('acquired', 'Acquired'), ('closed', 'Closed')], default='enquire', max_length=20),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('certificate', 'Certificate of Authenticity'), ('provenance', 'Provenance document'), ('condition', 'Condition report'), ('invoice', 'Historic invoice / record'), ('letter', 'Correspondence'), ('other', 'Supporting record')], default='other', max_length=40)),
                ('note', models.CharField(blank=True, help_text='One-line archival note.', max_length=300)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='collection.artifact')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
