# Generated by Django 5.1.15 on 2026-08-28 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_enquiry_stage_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending confirmation'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='artifact',
            name='bestseller',
            field=models.BooleanField(default=False, help_text='Featured in Best Sellers.'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='compare_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pre-sale price (₹); shown struck-through when set.', max_digits=10),
        ),
        migrations.AddField(
            model_name='artifact',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Acquisition price (₹).', max_digits=10),
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_snapshot', models.CharField(max_length=240)),
                ('price_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='collection.artifact')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='collection.order')),
            ],
        ),
    ]
