# Generated by Django 5.1.15 on 2026-08-29 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_order_artifact_bestseller_artifact_compare_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='artifact',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='bestseller',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='compare_price',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='price',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderLine',
        ),
    ]
