# Generated by Django 5.1.15 on 2026-08-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_remove_orderline_order_remove_orderline_artifact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='image_credit',
            field=models.CharField(blank=True, help_text='Credit line required by source.', max_length=300),
        ),
        migrations.AddField(
            model_name='artifact',
            name='image_license',
            field=models.CharField(blank=True, help_text='e.g. Open Access CC0.', max_length=120),
        ),
        migrations.AddField(
            model_name='artifact',
            name='image_source',
            field=models.CharField(blank=True, help_text='Holding institution of the reference photograph.', max_length=200),
        ),
        migrations.AddField(
            model_name='artifact',
            name='image_source_url',
            field=models.URLField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='artifact',
            name='rights_verified',
            field=models.BooleanField(default=False, help_text='License checked for this image.'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='frame_count',
            field=models.PositiveIntegerField(default=1, help_text='Photograph frames available (1 for still photography).'),
        ),
    ]
